remote_theme: Scriptor-Jekyll-Theme
title: "VisuaLore"
author: Damitr
description: "VisuaLore is a space dedicated to exploring the stories with & within visuals." 
# Site language
lang: en-GB

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Tags
    url: /tags/


    # Site footer
footer:
  content: "Text annotation Creative Commons Share Alike 4.0. Images mostly Public Domain unless otherwise mentioned."
  has_social: false

  # Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'

# Permalinks
permalink: /:title

# Conversion
markdown: kramdown
