
title: "VisuaLore"
author: "Damitr"
description: "VisuaLore is a space dedicated to exploring the stories with & within visuals." 
# Site language
lang: en-GB

# Site footer
footer:
  content: "Text annotation Creative Commons Share Alike 4.0. Images mostly Public Domain unless otherwise mentioned."
  has_social: false

markdown: kramdown
